/* Exercices de rasgueado de Gerardo Núñez (© Encuentro Productions), transcrits en code Compás.
   Fichier à part : il peut rester hors du dépôt public et être importé dans la bibliothèque. */
window.NUNEZ={coll:"Gerardo Núñez — Rasgueados",palos:["Soleá por bulería","Bulería","Soleá","Alegrías"],note:"Liaisons de prolongation : la note n'est pas rejouée. Ligados (notes liées de hauteur différente) : ils comptent comme des frappes, le micro les entend. × sur la partition = coup étouffé, compté comme une frappe.",
exos:[
 ["gn-759","Exercice 759 — a m i en doubles croches","759","3/4 | c:o c:xx n n:o | c:o c:xx c c:xx n |",70,
  "a m ↑↑ · i ↑  |  a m ↑↑ · i ↑ · a m ↑↑ · i ↑"],
 ["gn-760","Exercice 760 — a m i en triolets","760","3/4 | c:o c:xxx n n:o | c:o c:xxx c c:xxx n |",70,
  "a m i ↑↑↑ (triolet) · i ↓  |  a m i ↑↑↑ · i ↓ · a m i ↑↑↑ · i ↓"],
 ["gn-761","Exercice 761 — a m i i continu","761","3/4 | n:xxxx n:xxxx n:xxxx |",70,
  "a m i i ↑↑↑↓ × 3"],
 ["gn-762","Exercice 762 — a i i en triolets","762","3/4 | n:xxx n:xxx n:xxx |",70,
  "a i i ↑↑↓ × 3"],
 ["gn-763","Exercice 763 — abanico p a i","763","3/4 | n:xxx n:xxx n:xxx |",70,
  "Abanico (A) : p ↓ a ↑ i ↑ × 3"],
 ["gn-764","Exercice 764 — a i p en triolets","764","3/4 | n:xxx n:xxx n:xxx |",70,
  "a ↑ i ↑ p ↓ × 3"],
 ["gn-765","Exercice 765 — p a m i continu","765","3/4 | n:xxxx n:xxxx n:xxxx |",70,
  "p ↓ a ↑ m ↑ i ↑ × 3"],
 ["gn-766","Exercice 766 — abanico A2 p m p","766","3/4 | c:xxx c:xxx c:xxx c:xxx c:xxx c:xxx |",60,
  "Abanico A2 : p ↓ m ↑ p ↑ × 3, écrit en triolets de doubles croches — la figure de la partition (3/8) est jouée deux fois pour remplir une mesure de 3/4."],
 ["gn-767","Exercice 767 — abanico A2 p ami p","767","3/4 | c:xxx c:xxx c:xxx c:xxx c:xxx c:xxx |",60,
  "Abanico A2 : p ↓ ami ↑ p ↑ × 3, joué deux fois comme 766."],
 ["gn-768","Exercice 768 — ami p en croches","768","3/4 | n:xx n:xx n:xx |",70,
  "ami ↑ p ↓ × 3"],

 ["gn-770","Étude 1 — falseta en arpège","770–777","3/4\n| n:xx n:xx n:xx | b.:xx-x-x | n:xx n:xx n:xx | b.:xx-x-x\n| n:xx n:xx n:xx | b.:xx-x-x | b:xx-- n:o | b:o n:Xx |",80,
  "Arpège i a m sur la basse au pouce. La levée 769 (a m) précède la section. 777 : entrée du rasgueado ami ↑ p ↓."],
 ["gn-778","Étude 2 — rasgueado ami ↑ p ↓","778–785","3/4\n| n:ox n:xx n:xx | n:xx n:xx n:Xx | n:xx n:xx n:xx | n:xx n:xx n:Xx\n| n:xx n:xx n:xx | n:xx n:xx n:Xx | n:xx b:o | b:o n:xx |",80,
  "p ↓ puis ami ↑ p ↓ en croches, coups étouffés (×) et accords accentués sur le 3e temps de 779, 781, 783. 785 : deux basses, levée de la falseta."],
 ["gn-786","Étude 3 — falseta en arpège (II)","786–793","3/4\n| n:xx n:xx n:xx | b.:xx-x-x | n:xx n:xx n:xx | b.:xx-x-x\n| n:xx n:xx n:xx | b.:xx-x-x | b:xx-x n:xx | n:ox n n:xx |",80,
  "Arpège i a m, deuxième variation ; 792–793 : la note liée n'est pas rejouée."],
 ["gn-794","Étude 4 — falseta en arpège (III) et entrée","794–801","3/4\n| n:xx n:xx n:xx | b.:xx-x-x | n:xx n:xx n:xx | b.:xx-x-x\n| n:xx n:xx n:xx | b.:xx-x-x | b:xx-- n:o | n:oX n:xx n:xx |",80,
  "Arpège i a m ; 801 : entrée du rasgueado sur l'accord (p ↓), puis ami ↑ p ↓."],
 ["gn-802","Étude 5 — ami ↑ p ↓ et accords","802–809","3/4\n| n:xx n:xx n:xx | n:xx n:xx n:Xx | n:xx n:xx n:xx | n:xx n:xx n:Xx\n| n:xx n:xx n:xx | n:xx n:xx n:Xx | n:xx n:ox n:xx | n:xx n:xx n:oXx |",80,
  "ami ↑ p ↓ continu, accord sur le 3e temps des mesures paires. 808 : silence puis i ↓, ↑↓. 809 : ↑↓ ↑↓ puis triolet (silence) a ↑ i ↑."],
 ["gn-810","Étude 6 — triolets i a i et remate","810–817","3/4\n| n:xxx n n:oxx | n:xxx n n:oXx | n:xxx n n:oxx | n:xxx n n:oXx\n| n:xxx n n:oxx | n:xxx n n:Xo | b:o n:ooxx | n:xx n:xx n |",80,
  "Triolet i ↓ a ↑ i ↑, noire i ↓, triolet (silence) a ↑ i ↑. 815 : accord m ↑ étouffé. 816–817 : début de la falseta en ligados."],
 ["gn-818","Étude 7 — falseta en ligados","818–825","3/4\n| b.:ox-x-x | n:ox n:xx n | b.:xx-xxx | n:xx n:xx n:xx\n| n:xx n:xx n:xx | n:xx n:xx n:xx | n:oX b:xx-x | b:xx-x n:xx |",80,
  "Mélodie au pouce et i a m, accords ami ; 820 : ami ↑, i ↓, ami ↑. 824–825 : entrée du compás i ↓ ↑↓ ↓ ↑↓ ↓↑↓."],
 ["gn-826","Étude 8 — le rasgueado de compás","826–833","3/4\n| n:xxxx n:xxxx n:xx | b:ox-x n:xx | n:ox b:xx-x | b:xx-x n:xx\n| n:xxxx n:xxxx n:xx | b:ox-X n:xx | n:ox b:xx-X | b:xx-x n:xx |",80,
  "a m i i ↑↑↑↓ ×2, ↑↓ ; puis ↓ ↓↑↓ | ↓ ↑↓ ↓ | ↑↓ ↓↑↓. Les notes liées ne sont pas rejouées."],
 ["gn-834","Étude 9 — rasgueado et basses au pouce","834–841","3/4\n| n:xxxx n:xxxx n:xx | n:ox n:xx n:xx | b:xx-X n:xx | n:xX n:xx n:xx\n| b:oX-X n:xx | b.:xx-X-X | n:xx n:xx n:xx | b:x- n:Xx |",80,
  "a m i i ↑↑↑↓ ×2, ↑↓ ; accords p ↓ / p ↑ alternés avec la mélodie de basse au pouce (ligados)."],
 ["gn-842","Étude 10 — accords tenus et remate","842–849","3/4\n| b:ox-- n:X | b:ox-x n:xx | n:xx n:xx n:xx | b:x n:Xx\n| b:xX-- n:X | b:ox-x n:xX | b:ox-- n:xxxx | b. |",80,
  "i ↓, accord m ↑ tenu, i ↓ ↓ ↑↓ ; basses au pouce ; 846 : p ↓ m ↑ ; 848 : i ↓ puis a m i ↑↑↑ ; 849 : i ↓ final."],
 ["gn-850","Étude 11 — abanicos","850–857","3/4\n| n:Xxx n:xxx n | n:ox n:xx n:xx | n:ox n:xx n:xx | b:xX-x n:xx\n| n:oXx n:xxx n | n:ox n:xx n:ox | n:xx n:xx n:xx | b:xX-x n:xx |",70,
  "Abanico (A) en triolets, p ↓ sur le 3e temps ; i ↓ ↑↓ ↑↓ ; mélodie au pouce ; i ↓ ↓↑↓. 854 : a ↑ i ↑ sur le triolet."],
 ["gn-858","Étude 12 — rasgueado, pouce et abanico","858–865","3/4\n| n:Xxxx n:xxxx n:xx | n:oX n:xx n:xX | n:xx n:xx n:xx | b:xx-X n:xx\n| n:oXx n:xxx n:xxx | n:xxx n:xxx n | n:ox n:xx n:xx | b:oX-x n:xx |",80,
  "a m i i ×2, i ↑ i ↓ ; basses et accord p ↑ ; i ↓ ↑↓ ; 862–863 : abanico a ↑ i ↑ puis triolets, p ↓."],
 ["gn-866","Étude 13 — abanico et accords au pouce","866–873","3/4\n| n:oXx n:xxx n:xxx | n:xxx n:xxx n | n:oX n:Xx n:xx | b.:xX-X-o\n| n:oX n:Xx n:Xx | n:xx n:xx n | n:xx n:xx n:xx | b:X n:ox |",70,
  "Abanico a ↑ i ↑ + triolets, p ↓ ; accords p ↑ p ↓ ; i ↓ i ↓ ; 870–873 : accords ↑↓ et mélodie de basse au pouce."],
 ["gn-874","Étude 14 — mélodie au pouce et triolets","874–881","3/4\n| n n n:xx | n:xx n:xx n:xx | n:xx n:xx n:xx | b:xx-x n:xx\n| n:xX n n:Xx | b:ox-x n:xx | n:oxx n n:oxx | n:xxx n n:oxx |",80,
  "Mélodie au pouce avec ligados ; 878 : p ↓ ami ↑, m ↑ i ↓ ; 880–881 : triolets i ↓ a ↑ i ↑ et noires liées."],
 ["gn-882","Étude 15 — triolets liés et accords","882–889","3/4\n| n:xxx n n:oxx | n:xxx n n:oxx | n:xxx n:xxx n:xxx | n:xx n:xx n\n| n n:X n:Xx | b:ox-x n:Xx | n:ox b:Xx-X | n:oX n:xx n |",80,
  "i ↓ a ↑ i ↑, noire i ↓ liée, a ↑ i ↑ ; 885 : i ↓ m ↑ i ↓ m ↑ i ↑ ; 886–889 : accords m ↑ i ↑, compás, p ↓ ami ↑."],
 ["gn-890","Étude 16 — golpes et pouce","890–897","3/4\n| n:xxx n:xx n:ox | n:xo n:ox n:xo | n:xxx n:xx n:ox | n:xo n:xo n:xxx\n| n:xo n:oxx n:xxx | n:xo n:xo n:xxx | n n:xxx n:xxx | n:X n n:xx |",80,
  "ami ↑ p ↓ en triolets et croches ; les notes marquées d'un crochet « 4 » sont des golpes. 897 : accord ami ↑, ami ↑, i ↑ i ↓."],
 ["gn-898","Étude 17 — remate et compás","898–905","3/4\n| n:x-xx n n:Xx | b:xx-x n:Xx | n:xx n:xx n:xx | n:xx n:xx n:xx\n| n:xX n n:Xx | b:xx-x n:xX | n:ox b:xx-x | b:xx-x n:xx |",80,
  "i ↑ i ↓ a ↑ i ↑ ; compás ↑↓ ↑↓ ↓ ↑↓ ; basses au pouce ; 902 : p ↓ ami ↑ m ↑ i ↓ ; 903–905 : compás ↑ ↓ ↓ …"],
 ["gn-906","Étude 18 — rasgueado de compás sur accords","906–913","3/4\n| n:Xxxx n:xxxx n:xx | b:ox-x n:Xx | n:ox b:Xx-X | b:Xx-X n:Xx\n| n:Xxxx n:xxxx n:xx | b:ox-X n:xx | n:oX n:xx n:oX | b:ox-x n:xx |",80,
  "a m i i ↑↑↑↓ ×2, ↑↓ puis ↓ ↓ ↑↓ … ; les accords (X) tombent sur les accents du compás."],
 ["gn-914","Étude 19 — le même compás, autres accords","914–921","3/4\n| n:Xxxx n:xxxx n:xx | b:ox-X n:xx | n:oX b:xx-X | b:Xx-x n:xx\n| n:Xxxx n:xxxx n:xx | b:ox-X n:xx | n:oX b:xx-X | b:xx-x n:xx |",80,
  "a m i i ↑↑↑↓ ×2, ↑↓ ; ↓ ↓↑↓ | ↓ ↑↓ ↓ | ↑↓ ↓↑↓."],
 ["gn-922","Étude 20 — falseta au pouce","922–929","3/4\n| n:xxx n:xxx n:xxx | n:xxx n:xxx n:xxx | n:xxx n:xxx n:xxx | n:xx n:xx n:xx\n| n:xx n:xx n:xx | n:xx n:xx n:xx | n:xx n:xx n:xx | n n:X n:X |",80,
  "Triolets p (basse) · i (aiguë) · p ; 925–928 : mélodie au pouce avec ligados ; 929 : accords ami ↑ puis m ↑."],
 ["gn-930","Étude 21 — final","930–933","3/4\n| n:o b:X | b:X n:Xx | b:xoox n:xx | b.:o |",70,
  "Accord m ↑ (barré II), accord arpégé p, puis p ↓ · ami ↑ · p ↓ · ami ↑ p ↓ et dernier accord tenu."]
],
doigts:{
 "gn-759":"a↑ m↑ i↑ | a↑ m↑ i↑ a↑ m↑ i↑",
 "gn-760":"a↑ m↑ i↑ i↓ | a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓",
 "gn-761":"a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓",
 "gn-762":"a↑ i↑ i↓ a↑ i↑ i↓ a↑ i↑ i↓",
 "gn-763":"p↓ a↑ i↑ p↓ a↑ i↑ p↓ a↑ i↑",
 "gn-764":"a↑ i↑ p↓ a↑ i↑ p↓ a↑ i↑ p↓",
 "gn-765":"p↓ a↑ m↑ i↑ p↓ a↑ m↑ i↑ p↓ a↑ m↑ i↑",
 "gn-766":"p↓ m↑ p↑ p↓ m↑ p↑ p↓ m↑ p↑ p↓ m↑ p↑ p↓ m↑ p↑ p↓ m↑ p↑",
 "gn-767":"p↓ ami↑ p↑ p↓ ami↑ p↑ p↓ ami↑ p↑ p↓ ami↑ p↑ p↓ ami↑ p↑ p↓ ami↑ p↑",
 "gn-768":"ami↑ p↓ ami↑ p↓ ami↑ p↓",
 "gn-770":"i a m i a m | i a i m | i a m i a m | i a i m | i a m i a m | i a m m | i a | ami↑ p↓",
 "gn-778":"p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ | · ·",
 "gn-786":"i a m i a m | i a i m | i a m i a m | i a i m | i a m i a m | i · i m | i a m i a | m i a m",
 "gn-794":"i a m i a m | i a i m | i a m i a m | i a i m | i a m i a m | i a i m | i a | p↓ ami↑ p↓ ami↑ p↓",
 "gn-802":"ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ i↓ ↑ ↓ | ↑ ↓ ↑ ↓ a↑ i↑",
 "gn-810":"i↓ a↑ i↑ i↓ a↑ i↑ | i↓ a↑ i↑ i↓ a↑ i↑ | i↓ a↑ i↑ i↓ a↑ i↑ | i↓ a↑ i↑ i↓ a↑ i↑ | i↓ a↑ i↑ i↓ a↑ i↑ | i↓ a↑ i↑ i↓ m↑ | i · | · i a m i/p",
 "gn-818":"mi a a/p | m a m i | /p ami i↓ ami↑ /p | · · · · · · | · · · · · · | · · · · · i | i↓ ↑ ↓ ↓ | ↑ ↓ ↓ ↑ ↓",
 "gn-826":"a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓ ↑ ↓ | ↓ ↓ ↑ ↓ | ↓ ↑ ↓ ↓ | ↑ ↓ ↓ ↑ ↓ | a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓ ↑ ↓ | ↓ ↓ ↑ ↓ | ↓ ↑ ↓ ↓ | ↑ ↓ ↓ ↑ ↓",
 "gn-834":"a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓ ↑ ↓ | ↓ · ↓ ↑ ↓ | ↑ ↓ p↓ · · | · p↑ · · · i | ↑/p ↓ · · | · i ↑ ↓ | · · · · · · | · i↑ ↓",
 "gn-842":"i↓ m↑ | i↓ ↓ ↑ ↓ | /p · · · · · | · i↑ i↓ | · p↓ m↑ | i↓ i↓ /p i↓ | i↓ i↓ a↑ m↑ i↑ | i↓",
 "gn-850":"· · · · · · p↓ | i↓ ↑ ↓ ↑ ↓ | /p · · · · | · i↓ ↓ ↑ ↓ | a↑ i↑ · · · p↓ | i↓ ↑ ↓ · | · · · · · · | · i↓ ↓ ↑ ↓",
 "gn-858":"a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓ i↑ i↓ | i↓ · · · p↑ | · · · · · · | · i i↓ ↑ ↓ | a↑ i↑ · · · · · · | · · · · · · p↓ | · · · · · | i↓ ↓ ↑ ↓",
 "gn-866":"a↑ i↑ · · · · · · | · · · · · · p↓ | p↑ p↓ · · · | · i↓ i↓ | ↑/p ↓ · ↑ ↓ | · · · · · | · · · · · · | ↑ i",
 "gn-874":"/p · · · | · · · · · · | · · · · · · | · i · · i | · p↓ am↑ m↑ i↓ | ↓ ↓ ↑ ↓ | a↑ i↑ i↓ a↑ i↑ | i↓ a↑ i↑ i↓ a↑ i↑",
 "gn-882":"i↓ a↑ i↑ i↓ a↑ i↑ | i↓ a↑ i↑ i↓ a↑ i↑ | i↓ a↑ i↑ i↓ a↑ i↑ i↓ a↑ i↑ | i↓ m↑ i↓ m↑ i↑ | m↑ i↑ m↑ i↓ | ↓ ↓ ↑ ↓ | ↓ ↑ ↓ ↓ | p↓ ami↑ p↓ ami↑",
 "gn-890":"ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ p↓ ami↑ | ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ ami↑ ami↑ p↓ ami↑ | p↓ ami↑ p↓ ami↑ p↓ ami↑ | p↓ ami↑ ami↑ p↓ ami↑ | p↓ ami↑ p↓ ami↑ p↓ ami↑ p↓ | ami↑ ami↑ i↑ i↓",
 "gn-898":"i↑ i↓ a↑ i↑ ↑ ↓ | ↑ ↓ ↓ ↑ ↓ | ↑ ↓ ↑ /p i /p | i /p · · · ↓ | · p↓ ami↑ m↑ i↓ | i↑ i↓ ↓ · ↓ | ↓ ↑ ↓ ↓ | ↑ ↓ ↓ ↑ ↓",
 "gn-906":"a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓ ↑ ↓ | ↓ ↓ ↑ ↓ | ↓ ↑ ↓ ↓ | ↑ ↓ ↓ ↑ ↓ | a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓ ↑ ↓ | ↓ ↓ ↑ ↓ | ↓ ↑ ↓ ↓ | ↓ ↓ ↑ ↓",
 "gn-914":"a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓ ↑ ↓ | ↓ ↓ ↑ ↓ | ↓ ↑ ↓ ↓ | ↑ ↓ ↓ ↑ ↓ | a↑ m↑ i↑ i↓ a↑ m↑ i↑ i↓ ↑ ↓ | ↓ ↓ ↑ ↓ | ↓ ↑ ↓ ↓ | ↑ ↓ ↓ ↑ ↓",
 "gn-922":"/p i /p · i /p · i /p | · · · · · · · · · | · · · · · · · · /p | · i · /p · · | /p · · · · · | · · · · · · | · · · · · · | · ami↑ m↑",
 "gn-930":"m↑ | p p p↓ | ami↑ p↓ ami↑ p↓ | "
}};
